<?php

/**
 * @file
 * Primary module hooks for Custom Event module.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function custom_event_theme(): array {
  return [
    'event' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for event templates.
 *
 * Default template: event.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the event information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_event(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function custom_event_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish events.
      $storage = \Drupal::entityTypeManager()->getStorage('event');
      $event_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($event_ids) as $event) {
        $event->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize events.
      $storage = \Drupal::entityTypeManager()->getStorage('event');
      $event_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($event_ids) as $event) {
        $event->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function custom_event_user_predelete(UserInterface $account): void {
  // Delete events that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('event');
  $event_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($event_ids)
  );
  // Delete old revisions.
  $event_ids = $storage->getQuery()
    ->allRevisions()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  foreach (array_keys($event_ids) as $revision_id) {
    $storage->deleteRevision($revision_id);
  }
}
