name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push PHP image
        run: |
          docker-compose build php
          docker-compose push php

      - name: Build and push all services
        run: docker-compose build
      - name: Start services
        run: docker-compose up -d
      - name: Wait for services to be up
        run: docker-compose run php sh -c 'while ! nc -z sonarqube 9001; do sleep 1; done'

      - name: Run PHPUnit
        run: docker-compose run php vendor/bin/phpunit

      - name: Run PHPCS
        run: docker-compose run php vendor/bin/phpcs

      - name: Run SonarQube Scanner
        run: docker-compose run sonar-scanner

      - name: Stop services
        run: docker-compose down
