name: PHP CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout PHP project
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mbstring, intl, zip, xdebug

    - name: Validate composer.json and composer.lock
      working-directory: ./drupal
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: drupal/vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/drupal/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      working-directory: ./drupal
      run: composer install --prefer-dist --no-progress

    - name: Run PHPCS
      working-directory: ./drupal
      run: |
        ./vendor/bin/phpcs --standard=Drupal src/
        ./vendor/bin/phpcs --standard=Drupal src/ --report=checkstyle --report-file=build/logs/phpcs.xml

    - name: Run PHPUnit tests
      working-directory: ./drupal
      run: ./vendor/bin/phpunit --log-junit build/logs/phpunit.xml
